### PR TITLE
proposed improvements to the JASA quarto template

### PR DESCRIPTION
**Pull request by nicholasjhorton**
I *love* the JASA quarto template and thank you profusely for putting it together.

I've been in touch with Eric Sampson (ASA Journals Manager) about updating their .tex template to account for a number of changes, including updating the refs to more relevant ones, listing of DOI's/URL's and capitalizing reference title words. I've also made some other light edits (wording re: BibTeX and inclusion of a figure generated in R).

I'd welcome any thoughts about whether it might be reasonable to make these changes to your excellent template.

### CODE REVIEW

**Comment by nicholasjhorton** [comment]
I concur: I've removed the R code chunk for the reasons that you propose.

I will push my commit with these changes.

**Comment by nicholasjhorton** [comment]
Can you please let me know if the most recent commit (https://github.com/quarto-journals/jasa/pull/2/commits/e3b05b87de1c8f5bb76e14596eda8881cefa2d54) addresses your suggestions?

**Review by cderv — COMMENTED** [review]
Yes this looks good thank you. 

> I've been in touch with Eric Sampson (ASA Journals Manager) about updating their .tex template to account for a number of changes, including updating the refs to more relevant ones, listing of DOI's/URL's and capitalizing reference title words.

Sorry I may have missed something: Should we do some update to the tex template partials on this extension so that we are in sync with the updated template you contributed too ? Is this for another PR ?

**Comment by cderv** [comment]
Oh ok. I did not recall we did specific changes to the official template, but really this was @dragonstyle working on this in the first place. That would be him to credit. 

@dragonstyle do your remember adapting the JASA template specifically ? 

I believe we would need to do a check when the official `.tex` template will be modified so that we are sure to be in sync. It can come in another work probably.

**Review by cderv — APPROVED** [review]

**Comment by dragonstyle** [comment]
- For the underlying `tex` template, we did work to match the appearance of the JASA template but we more less just fine tuned our current template with title / include customization. Very happy to keep this in sync as we'd love for Quarto to be a great to submit JASA articles.
- Our `template.qmd` should stay in sync with JASA - happy here as well to accept PRs (like this ty!) or make changes to keep it in sync.
- The changes to support JASA were minimal so you're certainly welcome to credit me but the changes were largely merging pandoc's core template with the JASA tex and ensuring we're generating functional LaTeX, so not a ton of new creative work...

**Pull request merged**
